# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Class-SingletonRows
version:      0.11
version_from: lib/DBIx/Class/SingletonRows.pm
installdirs:  site
requires:
    DBD::SQLite:                   0
    DBI:                           0
    DBIx::Class:                   0
    Digest::MD5:                   0
    File::Temp:                    0
    Scalar::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
